- name: Deploy Docker Flask app
  hosts: web
  become: yes

  vars:
    container_name: myapp
    image_name: lilaczhang/zzw-myapp:latest
    host_port: "5000"
    container_port: "5000"

  tasks:
    - name: Ensure docker is installed
      dnf:
        name: docker
        state: present

    - name: Ensure docker is enabled and started
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Pull latest Docker image
      command: docker pull {{ image_name }}

    - name: Stop old container if exists
      shell: docker stop {{ container_name }} || true

    - name: Remove old container if exists
      shell: docker rm {{ container_name }} || true

    - name: Run new container
      command: >
        docker run -d
        -p {{ host_port }}:{{ container_port }}
        --name {{ container_name }}
        {{ image_name }}